name: city_issue_tracker_clean
description: "Malatya Büyükşehir Belediyesi için geliştirilen mobil sorun bildirim uygulaması"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.1.0
  # UI
  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Kamera & Medya
  image_picker: ^1.1.2

  # Konum & Harita
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1

  # Offline DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/core/localization/lang/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  min_sdk_android: 21
